; Project Nira — PlatformIO Configuration
; SPDX-License-Identifier: GPL-3.0-or-later

[env:esp32-s3-devkitc-1]
platform  = espressif32
board     = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed  = 921600
lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -std=gnu++17
monitor_filters = send_on_enter
